version: '3.8'

services:
  ib-tws:
    # ib-gateway or ib-tws. latest or stable.
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        PROGRAM: tws
        RELEASE: stable
        ARCH: x64
    container_name: tws
    env_file:
      - /opt/app/trading-app/.env
    restart: always
    network_mode: host
    environment:
      # User `uid` to run the container as (1000 is host user)
      PUID: 1000
      # User `gid` to run the container as (1000 is host user)
      PGID: 1000
      # VNC server password. If not defined, then VNC server will NOT start.
      VNC_PWD: tws
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x16}
      DISPLAY: :0
      TZ: ${TIME_ZONE:-America/New_York}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      # JVM options to prevent crashes
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+DisableAttachMechanism -Djava.awt.headless=false -Dsun.java2d.xrender=false -Dprism.order=sw"
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      # yes or no. See https://github.com/IbcAlpha/IBC/blob/master/userguide.md
      READ_ONLY_API: ${READ_ONLY_API:-no}
      # 'exit' or 'restart', set to 'restart if you set `AUTO_RESTART_TIME`. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      # time to restart IB Gateway, does not require daily 2FA validation. format hh:mm AM/PM. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#ibc-user-guide)
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      # Auto-Logoff: at a specified time, TWS shuts down tidily, without restarting
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      # a time (specified in your local timeframe) that is after 01:00 US/Eastern. When
      # this time is reached on Sundays, IBC tidily closes TWS, and the script then
      # reloads IBC thus starting a new instance of TWS and initiating the usual full logon.
      COLD_RESTART_TIME: ${COLD_RESTART_TIME:-}
      # Settings relate to the corresponding 'Precautions' checkboxes in the API section of the Global Configuration dialog. Accepted values `yes`, `no` if not set, the existing TWS/Gateway configuration is unchanged
      BYPASS_WARNING: ${BYPASS_WARNING:-yes}
      # automatically save its settings on a schedule of your choosing. You can specify one or more specific times, ex `SaveTwsSettingsAt=08:00   12:30 17:30`
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-Every 30 mins}
      # support relogin after timeout. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      IB_USER: ${IB_USER}
      IB_PASSWORD: ${IB_PASSWORD}
      # Port forwarding configuration
      ENABLE_SOCAT: ${ENABLE_SOCAT:-yes}
      # SSH Tunnel Configuration
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-20}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-3}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_PASSPHRASE_FILE: ${SSH_PASSPHRASE_FILE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-5}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
      SSH_RDP_PORT: ${SSH_RDP_PORT:-}
      SUPERVISORD_UI_USER: serveradmin
      SUPERVISORD_UI_PASS: serveradmin
      SUPERVISORD_UI_PORT: 9123
    # volumes:
      # Uncomment to mount SSH keys for tunnel authentication
      # - ${HOME}/.ssh:/home/ibuser/.ssh:ro
      # Uncomment to preserve TWS settings
      # - ./tws_settings:/home/ibuser/tws_settings
