version: "3.4"

services:
  ib-gateway:
    image: ib-gateway:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROGRAM=ibgateway
        - RELEASE=latest
        - VERSION=10.29.1f
    network_mode: host
    command: "ibc_ibgateway"
    environment:
      # User `uid` to run the container as (1000 is host user)
      PUID: 1000
      # User `gid` to run the container as (1000 is host user)
      PGID: 1000
      # VNC server password. If not defined, then VNC server will NOT start.
      VNC_PWD: ${VNC_PWD}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x16}
      DISPLAY: :1
      TZ: ${TIME_ZONE:-America/New_York}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      # Set Java heap, default 768MB, TWS might need more. Proposed value 1024. Enter just the number, don't enter units, ex mb. See [Increase Memory Size for TWS](https://ibkrguides.com/tws/usersguidebook/priceriskanalytics/custommemory.htm)
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      ## IBC variables ##
      # The TWS username.
      IB_USER: ${IB_USER}
      # The TWS password.
      IB_PASSWORD: ${IB_PASSWORD}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      # TWS_SETTINGS_PATH` is set and stored in a volume, jts.ini will already exists so this will not be used. Examples `Europe/Paris`, `America/New_York`, `Asia/Tokyo`
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      # yes or no. See https://github.com/IbcAlpha/IBC/blob/master/userguide.md
      READ_ONLY_API: ${READ_ONLY_API:-no}
      # 'exit' or 'restart', set to 'restart if you set `AUTO_RESTART_TIME`. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      # time to restart IB Gateway, does not require daily 2FA validation. format hh:mm AM/PM. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#ibc-user-guide)
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      # Auto-Logoff: at a specified time, TWS shuts down tidily, without restarting
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      # Settings relate to the corresponding 'Precautions' checkboxes in the API section of the Global Configuration dialog. Accepted values `yes`, `no` if not set, the existing TWS/Gateway configuration is unchanged
      BYPASS_WARNING: ${BYPASS_WARNING:-yes}
      # automatically save its settings on a schedule of your choosing. You can specify one or more specific times, ex `SaveTwsSettingsAt=08:00   12:30 17:30`
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-Every 30 mins}
      # support relogin after timeout. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
  ib-tws:
    image: ib-tws:stable
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROGRAM=tws
        - RELEASE=latest
    network_mode: host
    init: true
    command: "ibc_tws"
    environment:
      # User `uid` to run the container as (1000 is host user)
      PUID: 1000
      # User `gid` to run the container as (1000 is host user)
      PGID: 1000
      # VNC server password. If not defined, then VNC server will NOT start.
      VNC_PWD: ${VNC_PWD}
      VNC_SCREEN_DIMENSION: ${VNC_SCREEN_DIMENSION:-1600x1200x16}
      DISPLAY: :1
      TZ: ${TIME_ZONE:-America/New_York}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      # Set Java heap, default 768MB, TWS might need more. Proposed value 1024. Enter just the number, don't enter units, ex mb. See [Increase Memory Size for TWS](https://ibkrguides.com/tws/usersguidebook/priceriskanalytics/custommemory.htm)
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      ## IBC variables ##
      # The TWS username.
      IB_USER: ${IB_USER}
      # The TWS password.
      IB_PASSWORD: ${IB_PASSWORD}
      # live or paper.
      TRADING_MODE: ${TRADING_MODE:-paper}
      # TWS_SETTINGS_PATH` is set and stored in a volume, jts.ini will already exists so this will not be used. Examples `Europe/Paris`, `America/New_York`, `Asia/Tokyo`
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      # yes or no. See https://github.com/IbcAlpha/IBC/blob/master/userguide.md
      READ_ONLY_API: ${READ_ONLY_API:-no}
      # 'exit' or 'restart', set to 'restart if you set `AUTO_RESTART_TIME`. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      # time to restart IB Gateway, does not require daily 2FA validation. format hh:mm AM/PM. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#ibc-user-guide)
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      # Auto-Logoff: at a specified time, TWS shuts down tidily, without restarting
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      # Settings relate to the corresponding 'Precautions' checkboxes in the API section of the Global Configuration dialog. Accepted values `yes`, `no` if not set, the existing TWS/Gateway configuration is unchanged
      BYPASS_WARNING: ${BYPASS_WARNING:-yes}
      # automatically save its settings on a schedule of your choosing. You can specify one or more specific times, ex `SaveTwsSettingsAt=08:00   12:30 17:30`
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-Every 30 mins}
      # support relogin after timeout. See IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
