name: Gateway Latest Build

on:
    workflow_dispatch:
      inputs:
        tag_name:
          description: 'GitHub release tag'
          required: false
    release:
      types: [created]

jobs:
  build_gateway_latest_release:
    runs-on: ubuntu-latest
    if: startsWith(${{ github.event.release.tag_name}}${{ github.event.inputs.tag_name}}, 'latest-')
    steps:
        - name: Parse Release Name
          id: parse_release_name
          run: |
            release_name="${{ github.event.release.tag_name }}${{ github.event.inputs.tag_name }}"
            echo "Building Gateway latest for release: $release_name"
            version="${release_name#*-}"
    
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "Extracted version: $version"

            major_minor_version=$(echo "$version" | grep -oP '^\d+\.\d+')
            echo "Extracted major+minor version: $major_minor_version"
            echo "major_minor_version=$major_minor_version" >> $GITHUB_OUTPUT

            major_version=$(echo "$major_minor_version" | grep -oP '^[0-9]+')
            echo "Extracted major version: $major_version"
            echo "major_version=$major_version" >> $GITHUB_OUTPUT
          shell: bash

        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build and push Gateway latest
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            file: ./Dockerfile
            push: true
            build-args: |
                PROGRAM=gateway
                RELEASE=latest
                VERSION=${{ steps.parse_release_name.outputs.version }}
            tags: |
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:latest
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:${{ steps.parse_release_name.outputs.version }}
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:${{ steps.parse_release_name.outputs.major_minor_version }}


