name: Gateway Build

on:
    workflow_dispatch:
      inputs:
        tag_name:
          description: 'GitHub release tag'
          required: false
    release:
      types: [created]

jobs:
  build_gateway_release:
    runs-on: ubuntu-latest
    steps:
        - name: Parse Release Name
          id: parse_release_name
          run: |
            release_name="${{ github.event.release.tag_name }}${{ github.event.inputs.tag_name }}"
            release_type="${release_name%%-*}"
            echo "Building Gateway $release_type for release: $release_name"
            echo "release_type=$release_type" >> $GITHUB_OUTPUT

            version="${release_name#*-}"
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "Extracted version: $version"

            major_minor_version=$(echo "$version" | grep -oP '^\d+\.\d+')
            echo "Extracted major+minor version: $major_minor_version"
            echo "major_minor_version=$major_minor_version" >> $GITHUB_OUTPUT
          shell: bash

        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Gateway
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            file: ./build/Dockerfile
            push: true
            build-args: |
                PROGRAM=ibgateway
                RELEASE=${{ steps.parse_release_name.outputs.release_type }}
                VERSION=${{ steps.parse_release_name.outputs.version }}
            tags: |
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:${{ steps.parse_release_name.outputs.release_type }}
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:${{ steps.parse_release_name.outputs.version }}
                ${{ secrets.DOCKERHUB_USERNAME }}/ib-gateway:${{ steps.parse_release_name.outputs.major_minor_version }}
